### ISSUE TITLE
Bug bounty of $200 for memory leak

### ISSUE THREAD

**Issue by starl33t** [starl33t/starapp#2]
I have a calendarView.swift that suffers from a memory leak:
https://github.com/starl33t/starapp.git

1) How to reproduce it?
Navigate to calendar and scroll around. Over time the memory allocation grows.

2) What happens?
"Call stack limit reached" The allocation tree displays trends of a recursive call. Eventually, the app freezes.

3) What needs to be done?
Get rid of the memory leak while preserving all native functions. Memory should not be over 50 MB.

**Comment by mohammedalwaili92** [comment]
I'd rewrite the 3rd requirement and remove the "50 MB" requirement. 
The focus should be on the leaks and the unnecessary allocation of memory. If it goes above 50 MB that is still not an issue.

**Comment by starl33t** [comment]
Not necessarily for this particular calendar but given the allocation tree is growing as the functionality expands then the estimated memory should not be above 50 MB but you're right: the main priority is to stop accumulation of memory.

**Comment by ahmadishfaq1** [comment]
Hey Peter I have fixed the issue

**Comment by ahmadishfaq1** [comment]
I have removed the var visibleDays and calculation of day on scrolling.

**Comment by ahmadishfaq1** [comment]
visibleDays were calculated to get the day and day was used to get the daysOfYear.
When user comes to screen first time we show him current date and user can scroll up down in the current year. 
daysOfYear will only change when user selects a date from date picker. At that point daysOfYear are already being calculated. 
So on scroll there is no need to calculate these and these were causing memory issue while scrolling.

**Comment by ahmadishfaq1** [comment]
Do you want to push the code ?

**Comment by ahmadishfaq1** [comment]
> Not necessarily for this particular calendar but given the allocation tree is growing as the functionality expands then the estimated memory should not be above 50 MB but you're right: the main priority is to stop accumulation of memory.

Hey Peter I have fixed the issue.
I have removed the var visibleDays and calculation of day on scrolling.
visibleDays were calculated to get the day and day was used to get the daysOfYear.
When user comes to screen first time we show him current date and user can scroll up down in the current year.
daysOfYear will only change when user selects a date from date picker. At that point daysOfYear are already being calculated.
So on scroll there is no need to calculate these and these were causing memory issue while scrolling.

**Comment by starl33t** [comment]
Hey Ahmad
I think this sounds like a plausible solution since visibleDays is tied to daysOfYear through date.
Can you push the code so we can check?

**Comment by ahmadishfaq1** [comment]
sure

**Comment by ahmadishfaq1** [comment]
can you give me access to the code repo ?

**Comment by ahmadishfaq1** [comment]
Thanks for the invite! I am going to push the code shortly on top of that can you share your email, slack or skype e.t.c so that we an communicate swiftly! Thanks

**Comment by ahmadishfaq1** [comment]
The fix is pushed on branch [scroll-memory-fix](https://github.com/starl33t/starapp/tree/scroll-memory-fix)

**Comment by starl33t** [comment]
You can mail us: pt@starleet.com

We would need some time to check the code. If the bug is fixed then I will close the issue and wire the reward.

**Comment by ahmadishfaq1** [comment]
sure take your time

**Comment by ahmadishfaq1** [comment]
Let me know if you need more help in this or any other project! Thanks

**Comment by starl33t** [comment]
By removing the visible dates the code is not preserving the native function of the datepicker.
As the user scrolls through the calendar  then the date pickers month is fixed at July 2024. We need the datepicker to follow the current displayed month on the calendar. Also, the max call stack is still being reached. 

I will have to keep the bug bounty ongoing but thanks for looking into this.

**Comment by ahmadishfaq1** [comment]
Can you send me a video for the max call stack scenario?

**Comment by starl33t** [comment]
Here's how to look in to memory allocation:
1) Build the app
2) Navigate to "Memory" under debug
3) Click on "Profile in instruments"
4) Look at Allocations List

It's possible to build directly for profiling as well.

<img width="1271" alt="Screenshot 2024-07-26 at 15 57 52" src="https://github.com/user-attachments/assets/59cb61da-7c3c-4169-ab42-26d7b559de32">

**Comment by ahmadishfaq1** [comment]
The issue is produced due to
@Query private var sessions: [Session]
It is used to fetch data from the “SwiftData”.
When we don’t fetch data, Calendar seems to work smoothly without the memory issue.
But when we fetch data using @Query and the scrollview is scrolled , it starts fetching data continuously because this variable is used to mark the sessions on the date.

**Comment by starl33t** [comment]
@Query is used by SwiftData to fetch data from a database. In this case, it's Cloudkit. 

Other pages are using @Query too without any issue. However, there might be an issue with a nested ForEach-loop (days and daySessions). A consolidation of the two might be an answer or omit the latter somehow.

**Comment by starl33t** [comment]
The bug have been fixed by using a cache for populating the session on the dates calendar.
Please look at the latest commit.

@ahmadishfaq1 You pointed out the memory issue related to sessions and came very close to the solution so we would like to express our gratitude and provide 50% of the bug bounty. 
Please reach out to pt@starleet.com 

Closing the thread.
